services:
  backend-server:
    container_name: gametable-backend-server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env:ro
      - ./backend/tests:/app/tests
    depends_on:
      - mysql8_database

  mysql8_database:
    image: mysql:8.4
    container_name: gametable-mysql8-database
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql8_data:/var/lib/mysql

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: gametable-mongodb-database
    restart: unless-stopped
    env_file: ".env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=gametable
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend-server:
    container_name: gametable-frontend-server
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/bun.lock:/app/bun.lock:ro
      - /app/node_modules
    environment:
      # point the frontend to the backend service name inside the compose network
      VITE_API_BASE_URL: http://backend-server:8000
    depends_on:
      - backend-server

volumes:
  mysql8_data:
    name: semester_project_mysql_data
  mongo_data:
    name: semester_project_mongo_data
