services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/.env:/app/.env:ro #maybe no need to change? time will tell after graph and neo implementaiton
    # TODO: Add tests here when time comes. ./tests:/app/tests
    environment:
      DB_MODE: "neo" #todo or "mongo" or "neo" # this should change what is in the .env dynamically
    depends_on:
      - database

  database:
    image: mysql:8.4
    container_name: 1st_semester_exam_mysql8
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql8_data:/var/lib/mysql

volumes:
  mysql8_data:
    name: semester_project_mysql_data
