[project]
name = "mysql-to-nosql-migration"
version = "1.0.0"
description = "Data migration from MySQL to MongoDB and Neo4j"
requires-python = ">=3.14"
dependencies = [
    "mysql-connector-python>=9.5.0",
    "pymongo>=4.15.4", 
    "neo4j>=6.0.3",
    "python-dotenv>=1.2.1",
]