name: Test Fest Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "backups/**"
      - "db/**"

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a
        with:
          version: "0.9.17"
          enable-cache: true

      - name: Install The Project
        run: uv sync --locked --all-extras --dev

      - name: Run Tests
        run: |
          uv run pytest --cov=backend \
            --cov-report=xml:coverage.xml

      - name: Run Bandit
        run: |
          uv run bandit -c bandit.yaml \
            -r backend NoSQLMigrator data-aggregator \
            --severity-level high

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
