name: Test Fest Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "backups/**"
      - "db/**"

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a
        with:
          version: "0.9.17"
          enable-cache: true

      - name: Install The Project
        working-directory: backend
        run: uv sync --locked --all-extras --dev

      - name: Run Tests
        working-directory: backend
        run: uv run pytest --cov=. --cov-report=xml:coverage.xml

      - name: Run Bandit
        run: |
          uv run bandit -c bandit.yaml \
            -r backend NoSQLMigrator data-aggregator \
            --severity-level high

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.python.coverage.reportPaths=backend/tests/reports/coverage.xml

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: backend/tests/reports/
          if-no-files-found: error
          retention-days: 14
# deploy:
#   name: deployment
#   runs-on: ubuntu-latest

#   steps:
#     - uses: actions/checkout@v5

#     - name: Set Up Docker Buildx
#       uses: docker/setup-buildx-action@v3
#
#     - name: Security Engineering
#       run: |
#         cat > backend/.env << 'EOF'
#         MYSQL_USER=${{ secrets.MYSQL_USER }}
#         MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
#         MYSQL_SERVER=${{ secrets.MYSQL_SERVER }}
#         MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}
#         MYSQL_PORT=${{ secrets.MYSQL_PORT }}
#         EOF
#
#     - name: Build Backend Image
#       run: |
#         docker build -t gametable-backend:${{ github.sha }} .
#         docker save gametable-backend:${{ github.sha }} -o gametable-backend-image.tar
#
#     - name: Tar Permissions fix
#       run: |
#         ls -la gametable-backend-image.tar
#         sudo chown gametable_user:gametable_user gametable-backend-image.tar || true
#         sudo chmod 644 gametable-backend-image.tar
#         ls -la gametable-backend-image.tar
#
#     - name: Copy Backend Image Tar To Server
#       uses: appleboy/scp-action@v0.1.7
#       with:
#         host: ${{ secrets.DEPLOY_HOST }}
#         username: ${{ secrets.DEPLOY_USER }}
#         key: ${{ secrets.DEPLOY_SSH_KEY }}
#         source: "gametable-backend-image.tar"
